"""
CPG Export Utilities.

Provides serialisation helpers for Code Property Graphs built with
:mod:`src.graph.cpg.builder`.  Supports JSON (for frontend visualisation),
DOT (for Graphviz rendering), and statistical summaries.
"""

from __future__ import annotations

import json
import logging
from collections import Counter
from typing import Any

import networkx as nx

logger = logging.getLogger(__name__)


def export_to_json(graph: nx.DiGraph, output_path: str) -> None:
    """Export a CPG to a JSON file suitable for frontend visualisation.

    The output schema mirrors a standard node-link format with separate
    ``nodes`` and ``edges`` arrays.  Each node carries the normalised CPG
    attributes (``id``, ``type``, ``code``, ``lineNumber``, ``columnNumber``);
    each edge carries ``source``, ``target``, and ``type``.

    Args:
        graph: The Code Property Graph to export.
        output_path: Destination file path.  Parent directories must exist.
    """
    nodes: list[dict[str, Any]] = []
    for node_id, attrs in graph.nodes(data=True):
        nodes.append(
            {
                "id": node_id,
                "type": attrs.get("type", "UNKNOWN"),
                "code": attrs.get("code", ""),
                "lineNumber": attrs.get("lineNumber", 0),
                "columnNumber": attrs.get("columnNumber", 0),
            }
        )

    edges: list[dict[str, Any]] = []
    for src, dst, attrs in graph.edges(data=True):
        edges.append(
            {
                "source": src,
                "target": dst,
                "type": attrs.get("type", "UNKNOWN"),
            }
        )

    payload: dict[str, Any] = {
        "nodes": nodes,
        "edges": edges,
        "metadata": {
            "node_count": graph.number_of_nodes(),
            "edge_count": graph.number_of_edges(),
            "source_path": graph.graph.get("source_path", ""),
            "language": graph.graph.get("language", ""),
        },
    }

    with open(output_path, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2, default=str)

    logger.info(
        "Exported CPG to JSON (%d nodes, %d edges): %s",
        graph.number_of_nodes(),
        graph.number_of_edges(),
        output_path,
    )


def export_to_dot(graph: nx.DiGraph, output_path: str) -> None:
    """Export a CPG to DOT format for Graphviz rendering.

    Nodes are labelled with their ``type`` and a truncated ``code`` snippet.
    Edge labels show the edge ``type`` (AST, CFG, DDG, etc.).

    Args:
        graph: The Code Property Graph to export.
        output_path: Destination ``.dot`` file path.
    """
    lines: list[str] = ["digraph CPG {", '  rankdir=TB;', '  node [shape=box, fontsize=10];']

    for node_id, attrs in graph.nodes(data=True):
        node_type = attrs.get("type", "UNKNOWN")
        code = attrs.get("code", "")
        # Truncate long code snippets for readability in the DOT output.
        if len(code) > 60:
            code = code[:57] + "..."
        # Escape characters that break DOT syntax.
        code = code.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
        label = f"{node_type}\\n{code}"
        safe_id = _dot_safe_id(node_id)
        lines.append(f'  {safe_id} [label="{label}"];')

    for src, dst, attrs in graph.edges(data=True):
        edge_type = attrs.get("type", "")
        safe_src = _dot_safe_id(src)
        safe_dst = _dot_safe_id(dst)
        lines.append(f'  {safe_src} -> {safe_dst} [label="{edge_type}"];')

    lines.append("}")

    with open(output_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))

    logger.info(
        "Exported CPG to DOT (%d nodes, %d edges): %s",
        graph.number_of_nodes(),
        graph.number_of_edges(),
        output_path,
    )


def cpg_stats(graph: nx.DiGraph) -> dict[str, Any]:
    """Compute summary statistics for a Code Property Graph.

    Args:
        graph: The CPG to analyse.

    Returns:
        A dictionary containing:

        - ``node_count``: total number of nodes.
        - ``edge_count``: total number of edges.
        - ``nodes_by_type``: ``Counter`` mapping node type to count.
        - ``edges_by_type``: ``Counter`` mapping edge type to count.
        - ``avg_in_degree``: mean in-degree across all nodes.
        - ``avg_out_degree``: mean out-degree across all nodes.
        - ``density``: graph density (ratio of existing to possible edges).
        - ``connected_components``: number of weakly connected components.
        - ``is_stub``: whether the graph was generated by the stub builder.
    """
    node_count: int = graph.number_of_nodes()
    edge_count: int = graph.number_of_edges()

    nodes_by_type: Counter[str] = Counter()
    for _, attrs in graph.nodes(data=True):
        nodes_by_type[attrs.get("type", "UNKNOWN")] += 1

    edges_by_type: Counter[str] = Counter()
    for _, _, attrs in graph.edges(data=True):
        edges_by_type[attrs.get("type", "UNKNOWN")] += 1

    avg_in_degree: float = 0.0
    avg_out_degree: float = 0.0
    if node_count > 0:
        avg_in_degree = sum(d for _, d in graph.in_degree()) / node_count
        avg_out_degree = sum(d for _, d in graph.out_degree()) / node_count

    num_components: int = (
        nx.number_weakly_connected_components(graph) if node_count > 0 else 0
    )

    return {
        "node_count": node_count,
        "edge_count": edge_count,
        "nodes_by_type": dict(nodes_by_type),
        "edges_by_type": dict(edges_by_type),
        "avg_in_degree": round(avg_in_degree, 4),
        "avg_out_degree": round(avg_out_degree, 4),
        "density": round(nx.density(graph), 6),
        "connected_components": num_components,
        "is_stub": graph.graph.get("stub", False),
    }


# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------


def _dot_safe_id(node_id: Any) -> str:
    """Convert an arbitrary node identifier to a DOT-safe string.

    DOT identifiers must start with a letter or underscore and contain
    only alphanumeric characters or underscores.  This helper prefixes
    numeric or otherwise unsafe IDs with ``n_``.

    Args:
        node_id: The raw node identifier from the graph.

    Returns:
        A string safe for use as a DOT node identifier.
    """
    s = str(node_id)
    # If the id is purely numeric or starts with a digit, prefix it.
    if s.isdigit() or (s and s[0].isdigit()):
        return f"n_{s}"
    # Replace any non-alphanumeric characters with underscores.
    return "".join(c if c.isalnum() or c == "_" else "_" for c in s)
